//getting all tasks
GET http://localhost:3030/tasks

###

//creating a new task
POST http://localhost:3030/tasks
Content-Type: application/json

{
    "text" : "get a life"
   
}

###
//completing a task
GET http://localhost:3030/tasks/complete/6371d6b67374fbdbee9a54e3

###
DELETE http://localhost:3030/tasks/delete/6371d6b67374fbdbee9a54e3
