//getting all users
GET http://localhost:3030/tasks

###

//creating a new user
POST http://localhost:3030/tasks
Content-Type: application/json

{
    "text" : "get a life"
   
}

###
DELETE http://localhost:3030/tasks/delete/6370f77462bb8340b7b557cc
